name: Docker Publish

on:
  push:
    branches: [ "main" ]  # adjust this if your main branch has a different name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push production Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mnfst-starter-server:prod
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}

    - name: Build and push development Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mnfst-starter-server:dev